name: melon-ticket

on:
  workflow_dispatch:

jobs:
  ticket:
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v3

      
name: Run melon-ticket-actions
      uses: mooyoul/melon-ticket-actions@main
      with:
        product-id: ${{ secrets.PRODUCT_ID }}
        schedule-id: ${{ secrets.ROUND_ID }}
        seat-id: '1' # 필요하면 여러개 시도하도록 코드 수정 필요
        slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
